### ISSUE TITLE
Can't get user positions

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1113]
augur-node console log:

{"id":21,"jsonrpc":"2.0","method":"getTradingHistory","params":{"sortBy":"timestamp","isSortDescending":true,"marketId":"0xffba90565a6420d0c4c1fe172dc111fbd10a4cd8"}}
{"id":22,"jsonrpc":"2.0","method":"getSyncData","params":null}
{"id":50,"jsonrpc":"2.0","method":"getCategories","params":{"universe":"0x3d777ea1541a7dec004972b283d53af3633b7531"}}
getter error:  TypeError: Cannot read property 'abs' of undefined
    at _.filter (/Users/bthaile/gitrepos/augur-node.git/src/server/getters/get-user-trading-positions.ts:116:46)
    at /Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:2935:13
    at /Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:3010:24)
    at /Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:4894:18
    at baseFilter (/Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:2934:7)
    at Function.filter (/Users/bthaile/gitrepos/augur-node.git/node_modules/lodash/lodash.js:9173:14)
    at /Users/bthaile/gitrepos/augur-node.git/src/server/getters/get-user-trading-positions.ts:114:35
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bthaile/gitrepos/augur-node.git/src/server/getters/get-user-trading-positions.ts:4:58)
{"id":51,"jsonrpc":"2.0","method":"getMarketsInfo","params":{"marketIds":["0x3998d099283e91235b736d75f9d2b64675f2663e","0x9b090fa8fd0b65987d9ae59ea522080636ace896","0x9d3a5181fa79573d5ec7413ffddb49235664a4e2","0x137d755072e1fe35f6c75dc0cd68a6b1544a43fe","0xb6d1a1e0297b26eec8a38d16b73887720eaa4526","0x8e7205e3ad32bcb482dae0e07101921fc9738a3e","0x4208a8a28638b0903ba928d0bc2669c0afd6077f","0xd79eb8739b493058762c3823416b17a7775ea156","0x5caaced8df40e090e1d8d31edda244f7bdcb290d"]}}
{"id":52,"jsonrpc":"2.0","method":"getTradingHistory","params":{"sortBy":"timestamp","isSortDescending":true,"marketId":"0x3998d099283e91235b736d75f9d2b64675f2663e"}}

this occurs when `getUserTradingPositions` is called from UI, looks like a simple null check is needed but there might be more to it. Not sure if it's a local issue.
options used to call are
{
earliestCreationTime: undefined
latestCreationTime: undefined
orderState: "ALL"
transactionType: "all"
account: '0xbd355a7e5a7adb23b51f54027e624bfe0e238df6'
universe: '0x3d777ea1541a7dec004972b283d53af3633b7531'
}
I'm on pop docker fake time.

**Comment by bthaile** [comment]
looks to be an issue in my local env. I'll keep an eye out.
