### ISSUE TITLE
populated geth image error: TypeError: Cannot read property 'toArray' of undefined

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#1409]
**Describe the bug** 
The following is failing:
node /augur/packages/augur-tools/scripts/dp create-markets

```
Creating buy orders - trade group ID 0xb4c4de22797e76096a1c3f5101829b6a3a51c97d7432824cc29f77a058c283bb
Creating orders for outcome 1
{"cost":"280000000000000","onChainAmount":"100000000000","onChainSharesProvided":"0","onChainPrice":"2800"}
price: 0.28 2800
amount: 0.001 100000000000
numTicks: 10000
cost: 0.00028 ETH
transaction failed: TypeError: Cannot read property 'toArray' of undefined
    at parseNumber (/augur/node_modules/ethereumjs-abi/lib/index.js:70:18)
    at encodeSingle (/augur/node_modules/ethereumjs-abi/lib/index.js:108:36)
    at Function.ABI.rawEncode (/augur/node_modules/ethereumjs-abi/lib/index.js:345:15)
    at abiEncodeData (/augur/node_modules/speedomatic/src/abi-encode-data.js:7:38)
    at Object.abiEncodeTransactionPayload (/augur/node_modules/speedomatic/src/abi-encode-transaction-payload.js:10:92)
    at /augur/node_modules/ethrpc/src/encode-request/package-request.js:28:21
    at store.dispatch (/augur/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at /augur/node_modules/ethrpc/src/transact/call-or-send-transaction.js:11:5
    at store.dispatch (/augur/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at /augur/node_modules/ethrpc/src/transact/call-contract-function.js:21:5 { constant: false,
  name: 'publicCreateOrder',
  inputs:
   [ '_type',
     '_attoshares',
     '_price',
     '_market',
     '_outcome',
     '_betterOrderId',
     '_worseOrderId',
     '_tradeGroupId',
     '_ignoreShares',
     '_kycToken' ],
  signature:
   [ 'uint8',
     'uint256',
     'uint256',
     'address',
     'uint256',
     'bytes32',
     'bytes32',
     'bytes32',
     'bool',
     'address' ],
  returns: 'bytes32',
  to: '0x905419e7A1f96A973AB8988Ba19C84135C6f7122',
  params:
   [ '0x0',
     '0x000000000000000000000000000000000000000000000000000000174876e800',
     '0x0000000000000000000000000000000000000000000000000000000000000af0',
     '0x93943fb2d02ce1101dadc3ab1bc3cab723fd19d6',
     '0x0000000000000000000000000000000000000000000000000000000000000001',
     '0x0000000000000000000000000000000000000000000000000000000000000000',
     '0x0000000000000000000000000000000000000000000000000000000000000000',
     '0xb4c4de22797e76096a1c3f5101829b6a3a51c97d7432824cc29f77a058c283bb',
     true,
     undefined ],
  from: '0x913da4198e6be1d5f5e4a40d0667f70c0b5430eb',
  gasPrice: 20000000000,
  uuid: '60aa4298-00b4-4082-9504-8f3579f7fcfc',
  send: false } undefined 0xaabe5845e26f0a1dab72b63e5614606727eb0b995838dddf234f0ea2c3270285
{
```

**Comment by nuevoalex** [comment]
Looked into this a bit but it appears there are a few problems preventing getting started on working through this:

augur-core is building to the wrong dir in augur-artifacts
augur.js will not build successfully for package dependency reasons.

In general we need to get to a state where this script (deploy and create-markets) can be run locally without error against a local POA node. Otherwise we can't reasonably keep this working.

I'm switching back to contract work since there's a soft deadline on wrapping that up and this could potentially take an unknown amount of time.

The following functions will need to be updated at some point to include these new params though for the time being only the ones preventing the populated docker image from build successfully need to be updated:
```
createDisputeWindow
	initial: boolean
	
finalizeFork replaced with finalize

get[.*]DisputeWindow
	initial: boolean

publicFillOrder
	affiliateAddress: string (address)

publicCreateOrder
	affiliateAddress: string (address)
	kycToken: string (address)
	
trade/fillBest functions
	affiliateAddress: string (address)
	kycToken: string (address)
	
get[.*]OrderId
	kycToken: string (address)
```
