### ISSUE TITLE
account/platform stats return empty values with error

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#1507]
![image.png](https://images.zenhubusercontent.com/5c00901a5cb43a45a18aeb7f/fcb7f7d1-a2ab-42af-81d5-e27ca543affe)

2 issues:

1. Inconsistently getting errors,
2. Volume shows for 1 month and all time, but not for 24 hour and 1 week.

below is an example of the error that sometimes occurs
```
{"id":312,"jsonrpc":"2.0","method":"getAccountTimeRangedStats","params":{"account":"0xbd355a7e5a7adb23b51f54027e624bfe0e238df6","universe":"0x3d777ea1541a7dec004972b283d53af3633b7531","startTime":1548857527,"endTime":1549462327}}

...
getter error:  Error: startTime/endTime error
    at /Users/bthaile/gitrepos/augur-node.git/src/server/getters/get-account-time-ranged-stats.ts:81:11
    at Generator.next (<anonymous>)
    at fulfilled (/Users/bthaile/gitrepos/augur-node.git/src/server/getters/get-account-time-ranged-stats.ts:4:58)
```

**Comment by brianosaurus** [comment]
Fixed volume and sorted out endTime values.
