### ISSUE TITLE
npm start fails due to missing chalk

### ISSUE THREAD

**Issue by vega113** [AugurProject/augur#226]
When executing instructions in README I get error
```
Yuris-MacBook-Pro:augur vega$ npm start

> augur@0.1.0 start /Users/vega/devroot/augur
> node server.js

module.js:338
    throw err;
          ^
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17
```

**Comment by tinybike** [comment]
Did you try running `npm install` first?  It should install the chalk package.

**Comment by vega113** [comment]
I think so.

**Comment by tinybike** [comment]
If you go to the augur directory and type `ls node_modules`, can you paste the output here?

**Comment by vega113** [comment]
Sure. 
```
Yuris-MacBook-Pro:augur vega$ ls node_modules
async				browserify			grunt				node-static			react-dom			ua-parser-js
augur-abi			chalk				grunt-browserify		pnglib				react-highcharts		web3
augur-contracts			envify				grunt-contrib-jshint		posix-getopt			react-intl
augur.js			es6-promise			jquery				react				react-paginate
babelify			fbjs				keythereum			react-bootstrap			react-router
bignumber.js			firebase-token-generator	lodash				react-cookie			react-tabs
bootstrap			fluxxor				moment				react-date-picker		secure-random
Yuris-MacBook-Pro:augur vega$ 
```

**Comment by tinybike** [comment]
Hm, chalk is in there.  I wonder why it's complaining about it.  Were you able to resolve this?  Your comments in the other issue indicate that you've got a local augur client installed and running.

**Comment by vega113** [comment]
Yes, I resolved it by installing chalk.
