### ISSUE TITLE
I cannot run a node to join the mainpage of Augur at http://localhost:9000/

### ISSUE THREAD

**Issue by jmiehau** [AugurProject/augur#35]
// I am sincronized at the Ethereum blockchain with Geth .28

But I get this log at the Augur Terminal. I am on OS X

INFO in augur [./augur.py:95]:
Found augur core at /Users/xx/augur/augur/core
--------------------------------------------------------------------------------
 * Running on http://127.0.0.1:9000/
 * Restarting with reloader
--------------------------------------------------------------------------------
INFO in augur [./augur.py:95]:
Found augur core at /Users/xx/augur/augur/core
--------------------------------------------------------------------------------
127.0.0.1 - - [2015-06-10 01:01:02] "GET / HTTP/1.1" 200 19711 0.030901
Traceback (most recent call last):
  File "/Users/xx/augur/augur/core/threads.py", line 10, in <module>
    import miner
  File "/Users/xx/augur/augur/core/miner.py", line 5, in <module>
    import blockchain
  File "/Users/xx/augur/augur/core/blockchain.py", line 6, in <module>
    import networking
  File "/Users/xx/augur/augur/core/networking.py", line 1, in <module>
    import socket, tools, custom, time, sys, select
  File "/Users/xx/augur/augur/core/tools.py", line 32, in <module>
    logging.basicConfig(filename=custom.log_file, level=logging.INFO)
  File "//anaconda/lib/python2.7/logging/__init__.py", line 1540, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "//anaconda/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "//anaconda/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/Users/xx/augur/augur/core/log'
127.0.0.1 - - [2015-06-10 01:02:12] "GET / HTTP/1.1" 200 19711 0.001016
Traceback (most recent call last):
  File "/Users/xx/augur/augur/core/threads.py", line 10, in <module>
    import miner
  File "/Users/xx/augur/augur/core/miner.py", line 5, in <module>
    import blockchain
  File "/Users/xx/augur/augur/core/blockchain.py", line 6, in <module>
    import networking
  File "/Users/xx/augur/augur/core/networking.py", line 1, in <module>
    import socket, tools, custom, time, sys, select
  File "/Users/xx/augur/augur/core/tools.py", line 32, in <module>
    logging.basicConfig(filename=custom.log_file, level=logging.INFO)
  File "//anaconda/lib/python2.7/logging/__init__.py", line 1540, in basicConfig
    hdlr = FileHandler(filename, mode)
  File "//anaconda/lib/python2.7/logging/__init__.py", line 911, in __init__
    StreamHandler.__init__(self, self._open())
  File "//anaconda/lib/python2.7/logging/__init__.py", line 936, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/Users/xx/augur/augur/core/log'

**Comment by joeykrug** [comment]
Hey, it seems you're on the really old prototype (back from Oct. / Nov.) our latest version is available here: https://github.com/AugurProject/augur-client.  

`geth --rpc --rpccorsdomain 'http://localhost:8080' --shh --networkid 1010101 --protocolversion 71 --datadir Documents/geth --unlock primary console` is an example of how you should start geth when using it btw --- it's on a private chain, also make sure to use a different datadir (it doesn't have to be Documents/geth, just make something up).  Note: your account on the private chain will be diff. than your regular ethereum account
