### ISSUE TITLE
flash connect error

### ISSUE THREAD

**Issue by bthaile** [AugurProject/augur#3554]
<https://gist.github.com/bthaile/7adb655d419e8bb9d9b47dcc9f95ae6b> 

```
(node:34346) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 closed listeners added. Use emitter.setMaxListeners() to increase limit
Error: once called more than once
    at /Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:198:13
    at /Users/bthaile/gitrepos/augur/node_modules/argsarray/index.js:14:18
    at args.(anonymous function) (/Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:262:7)
    at /Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:2140:14
    at /Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:5022:18
    at /Users/bthaile/gitrepos/augur/node_modules/argsarray/index.js:14:18
    at /Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:5101:16
    at /Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:4140:9
    at /Users/bthaile/gitrepos/augur/node_modules/pouchdb/lib/index.js:3971:13
error Command failed with exit code 1.
```

error trying to connect in flash, on master

**Comment by robert-e-davidson3** [comment]
This error occurs when setting up the SDK in flash. Somehow it's tied in with db setup in the SEO Connector. This error does not occur in the UI or the tests so it's flash-specific. It may be due to us setting up the databases twice.

**Comment by robert-e-davidson3** [comment]
Some helpful links:

* https://github.com/pouchdb/pouchdb/issues/7825
* https://github.com/pouchdb/pouchdb/issues/7819

**Comment by robert-e-davidson3** [comment]
Made a branch where forking works but the approach to fix it isn't viable. <https://github.com/AugurProject/augur/pull/3994>
