### ISSUE TITLE
Provide main net alternative to running local full node

### ISSUE THREAD

**Issue by adrake33** [AugurProject/augur#635]
@eyezick commented on [Wed Aug 08 2018](https://github.com/AugurProject/augur-node/issues/594)

OS: Ubuntu 16.0.4

On an untouched Ubuntu instance with a local Parity node, npm installed successfully. Below output is from executing `npm run clean-start`/setting up augur-node for first time.

```connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://localhost:8545","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
connected to ethereum
Deleting existing DB for this configuration as the upload block number is not equal: OLD: 0 NEW: 5926223
Moving database /home/ubuntu/augur-node/augur-1-2.db to /home/ubuntu/augur-node/backup-augur-1-1533755130009.db 2
(node:31515) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, rename '/home/ubuntu/augur-node/augur-1-2.db' -> '/home/ubuntu/augur-node/backup-augur-1-1533755130009.db 2'
(node:31515) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31515) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
/home/ubuntu/augur-node/augur-1-2.db
Getting Augur logs from block 5926223 to block 6112095
got 1156 logs in blocks { fromBlock: 6077535, toBlock: 6083294 }
Fetching blocks details from 6080002 to 6083282
new block: 6080002, 1533288120 (Fri Aug 03 2018 09:22:00 GMT+0000 (UTC))
Processing 3 logs
market and outcome not found for shareToken 0x19b11dc141d21e014faf08bd04185d635c58119a (0xe06c295508cf34df5b1bab4ee2b24b9772115a10a54336629e886bd94dba3e48
Stopping Augur Node Server
Unhandled rejection Error: market and outcome not found for shareToken 0x19b11dc141d21e014faf08bd04185d635c58119a (0xe06c295508cf34df5b1bab4ee2b24b9772115a10a54336629e886bd94dba3e48
    at db.first.from.where.asCallback (/home/ubuntu/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/home/ubuntu/augur-node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/ubuntu/augur-node/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/home/ubuntu/augur-node/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/ubuntu/augur-node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/augur-node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/augur-node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/augur-node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/augur-node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://localhost:8545","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
connected to ethereum
got 1156 logs in blocks { fromBlock: 6077535, toBlock: 6083294 }
Fetching blocks details from 6080002 to 6083282
got 1521 logs in blocks { fromBlock: 6083295, toBlock: 6089054 }
Fetching blocks details from 6083321 to 6089044
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-node@5.4.0-1 start: `node ./build/runServer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-node@5.4.0-1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-08T19_05_35_356Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-node@5.4.0-1 clean-start: `npm run rebuild && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-node@5.4.0-1 clean-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

NPM log below:

```0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'clean-start' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'preclean-start', 'clean-start', 'postclean-start' ]
5 info lifecycle augur-node@5.4.0-1~preclean-start: augur-node@5.4.0-1
6 info lifecycle augur-node@5.4.0-1~clean-start: augur-node@5.4.0-1
7 verbose lifecycle augur-node@5.4.0-1~clean-start: unsafe-perm in lifecycle true
8 verbose lifecycle augur-node@5.4.0-1~clean-start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/augur-node/node_modules/.bin:/home/ubuntu/bin:/home/ubuntu/.l$
9 verbose lifecycle augur-node@5.4.0-1~clean-start: CWD: /home/ubuntu/augur-node
10 silly lifecycle augur-node@5.4.0-1~clean-start: Args: [ '-c', 'npm run rebuild && npm start' ]
11 silly lifecycle augur-node@5.4.0-1~clean-start: Returned: code: 1  signal: null
12 info lifecycle augur-node@5.4.0-1~clean-start: Failed to exec clean-start script
13 verbose stack Error: augur-node@5.4.0-1 clean-start: `npm run rebuild && npm start`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid augur-node@5.4.0-1
15 verbose cwd /home/ubuntu/augur-node
16 verbose Linux 4.4.0-1061-aws
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "clean-start"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error augur-node@5.4.0-1 clean-start: `npm run rebuild && npm start`
22 error Exit status 1
23 error Failed at the augur-node@5.4.0-1 clean-start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]



```

---

@bthaile commented on [Thu Aug 09 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-411785714)

Are you using newest augur-node master branch?

---

@eyezick commented on [Thu Aug 09 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-411787746)

Git log shows latest `commit 2a4537d197ad0fc9fde3ce7d868785d1f803c459`

---

@bthaile commented on [Thu Aug 09 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-411789173)

That is up to date. If you run 
>npm run clean-start

Do you get the same error as if you run
>DELAY_WAIT_MILLIS=2000 npm run clean-start

---

@eyezick commented on [Fri Aug 10 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-412010126)

Yup; output below. 

Also btw, noticed the default URL for the websocket connection (when ETHEREUM_WS is undefined) is an HTTP link `"http://localhost:8546"`but it should be a WS link right?

```
$ DELAY_WAIT_MILLIS=2000 npm run clean-start

> augur-node@5.4.0-1 clean-start /home/ubuntu/augur-node
> npm run rebuild && npm start


> augur-node@5.4.0-1 rebuild /home/ubuntu/augur-node
> npm run clean && npm run build


> augur-node@5.4.0-1 clean /home/ubuntu/augur-node
> rm -rf augur*.db build definitions


> augur-node@5.4.0-1 build /home/ubuntu/augur-node
> tsc


> augur-node@5.4.0-1 start /home/ubuntu/augur-node
> node ./build/runServer

connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://localhost:8545","ws":"ws://127.0.0.1:8546"}
websocket ws://127.0.0.1:8546 closed: 1006 connection failed
websocket ws://127.0.0.1:8546 closed: 1006 connection failed
connected to ethereum
/home/ubuntu/augur-node/augur-1-2.db
Getting Augur logs from block 5926223 to block 6121190
got 105 logs in blocks { fromBlock: 6075110, toBlock: 6080869 }
Fetching blocks details from 6080002 to 6080869
new block: 6080002, 1533288120 (Fri Aug 03 2018 09:22:00 GMT+0000 (UTC))
Processing 3 logs
market and outcome not found for shareToken 0x19b11dc141d21e014faf08bd04185d635c58119a (0xe06c295508cf34df5b1bab4ee2b24b9772115a10a54336629e886bd94dba3e48
Stopping Augur Node Server
Unhandled rejection Error: market and outcome not found for shareToken 0x19b11dc141d21e014faf08bd04185d635c58119a (0xe06c295508cf34df5b1bab4ee2b24b9772115a10a54336629e886bd94dba3e48
    at db.first.from.where.asCallback (/home/ubuntu/augur-node/build/blockchain/log-processors/order-created.js:20:29)
    at tryCatcher (/home/ubuntu/augur-node/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (/home/ubuntu/augur-node/node_modules/bluebird/js/release/nodeify.js:22:30)
    at Promise._settlePromise (/home/ubuntu/augur-node/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/home/ubuntu/augur-node/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/augur-node/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/ubuntu/augur-node/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/ubuntu/augur-node/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/ubuntu/augur-node/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

got 1730 logs in blocks { fromBlock: 6080870, toBlock: 6086629 }
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://localhost:8545","ws":"ws://127.0.0.1:8546"}
websocket ws://127.0.0.1:8546 closed: 1006 connection failed
websocket ws://127.0.0.1:8546 closed: 1006 connection failed
connected to ethereum
got 105 logs in blocks { fromBlock: 6075110, toBlock: 6080869 }
Fetching blocks details from 6080002 to 6080869
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-node@5.4.0-1 start: `node ./build/runServer`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-node@5.4.0-1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-10T08_04_57_845Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-node@5.4.0-1 clean-start: `npm run rebuild && npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-node@5.4.0-1 clean-start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-08-10T08_04_57_868Z-debug.log
```

---

@bthaile commented on [Fri Aug 10 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-412228974)

Augur-node can use http or Websockets. 
http":"http://localhost:8545","
ws":"ws://127.0.0.1:8546

These look correct depending on the parity setup. We’re investigating the correct setup for parity, so augur-node can process logs. 

---

@eyezick commented on [Sat Aug 11 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-412277366)

I understand it can use either, below are the default links when the environment variables are undefined. You're saying `"ws":"http://localhost:8546"` is correct?
```connecting to ethereum-node: {"http":"http://localhost:8545","ws":"http://localhost:8546"}```

And cool, I'll just use the public geth nodes until then.

---

@bthaile commented on [Sat Aug 11 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-412277416)

We are going to push out recommended arg for running local parity node. Stay tuned. 

---

@eyezick commented on [Sun Aug 19 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-414146665)

hi @bthaile , any eta?

---

@bthaile commented on [Sun Aug 19 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-414146953)

We have a draft fix for the .deb issue, just testing. Our usually .deb installer tester is out.

---

@eyezick commented on [Mon Sep 03 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-418174838)

@bthaile do you guys happen to know if there any other EC2 supported operating systems that are working with Parity & Augur-node?

---

@bthaile commented on [Mon Sep 03 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-418175080)

I’m not sure, @petong @epheph @pg might know. 

---

@adrake33 commented on [Thu Sep 13 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-421192227)

This is being tracked at https://app.clubhouse.io/augur/story/15116/github-parity-node-could-not-find-balance-for-token-decrease.

---

@adrake33 commented on [Mon Sep 24 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-424143920)

@eyezick Are you using warp sync? If so, the issue seems to be that you need to wait longer. Parity in warp sync will give the false impression of when it is ready because it is only up-to-date for new blocks, but not old blocks.  See here for more info: https://github.com/AugurProject/augur-app/issues/291#issuecomment-418540421.

There isn't really anything we can do to fix this, but @epheph recently created 2 PRs to let the user know that there's an issue with their Parity node: 
https://github.com/AugurProject/augur.js/pull/517
https://github.com/AugurProject/augur-node/pull/651

---

@adrake33 commented on [Wed Sep 26 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-424773387)

Closing this issue for now. @eyezick Please let me know if this should be reopened.

---

@eyezick commented on [Thu Dec 06 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-444892932)

@adrake33 I'm now having the same error with Infura.

This Augur Node has been running for days with this Infura provider, but today it keeps throwing this error.

I've further tried with multiple Infura endpoints, as well as `https://gethnode.com/http`

```
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/v3/******************","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
connected to ethereum
Found prior database: /home/ubuntu/augur-node/augur-1-2.db
/home/ubuntu/augur-node/augur-1-2.db
Starting websocket secure server on port 9002
Starting websocket server on port 9001
Getting Augur logs from block 6834717 to block 6837137
got 41 logs in blocks { fromBlock: 6834717, toBlock: 6834976 }
Fetching blocks details from 6834718 to 6834944
new block: 6834718, 1544072675 (Thu Dec 06 2018 05:04:35 GMT+0000 (UTC))
Processing 3 logs
market and outcome not found for shareToken 0xd6917729fdbdb8dd7f4a80a6472747838957af2b (0xfc8794e35702640666f5d4a23246f1ed7f26f4b8bed2d3c257ecb3734581ac09
Stopping Augur Node Server
got 58 logs in blocks { fromBlock: 6834977, toBlock: 6835696 }
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/v3/******************","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
connected to ethereum
got 41 logs in blocks { fromBlock: 6834717, toBlock: 6834976 }
Fetching blocks details from 6834718 to 6834944
got 58 logs in blocks { fromBlock: 6834977, toBlock: 6835696 }
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/v3/******************","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
connected to ethereum
got 41 logs in blocks { fromBlock: 6834717, toBlock: 6834976 }
Fetching blocks details from 6834718 to 6834944
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"https://mainnet.infura.io/v3/******************","ws":"http://localhost:8546"}
websocket http://localhost:8546 closed: 1006 connection failed
websocket http://localhost:8546 closed: 1006 connection failed
connected to ethereum
got 41 logs in blocks { fromBlock: 6834717, toBlock: 6834976 }
Fetching blocks details from 6834718 to 6834944
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! augur-node@7.1.5 start: `ts-node ./src/runServer && ETHEREUM_HTTP=https://mainnet.infura.io/v3/******************`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the augur-node@7.1.5 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ubuntu/.npm/_logs/2018-12-06T14_39_29_174Z-debug.log

```

---

@adrake33 commented on [Thu Dec 06 2018](https://github.com/AugurProject/augur-node/issues/594#issuecomment-444961944)

@eyezick We're in the process of transitioning to a new repository for version 2 of Augur: https://github.com/AugurProject/augur. As a result, we'd like to consolidate all of our tickets here (both for v1 and v2), so please file all future tickets in this repository. I'll go ahead and move this ticket over to the new repository. We'll also be adding a note to the old repositories to file tickets in the new one.

**Comment by adrake33** [comment]
@eyezick Gethnode is currently offline. (The Augur team does not run this server, so we have no control over it.) Infura is also unusable right now. We are currently looking into other alternatives. In the meantime, users can run a local full node or a hosted node they trust. We will provide an update once we have more info.

**Comment by adrake33** [comment]
Closing this since the Alchemy endpoint is now useable by selecting the mainnet option in Augur App.
