### ISSUE TITLE
augur-node start: Could not connect via augur.connect Error: Connection failed

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#643]
Ran into an issue using light node. started app with a full sync from about an hour previous. light node syncs and processes all market data fine, gives me the `open in browser` button. after a while it seems I lose peers and augur-node is unable to recover, leaving the app in a disconnected state.

The same behavior can be simulated by running the app and turning off networking.

```
09:31:46.007] [info] new block: 6843866, 1544203852 (Fri Dec 07 2018 09:30:52 GMT-0800 (PST))
[09:31:46.022] [info] new block: 6843867, 1544203895 (Fri Dec 07 2018 09:31:35 GMT-0800 (PST))
[09:31:46.031] [info] new block: 6843868, 1544203896 (Fri Dec 07 2018 09:31:36 GMT-0800 (PST))
[09:31:46.040] [info] new block: 6843869, 1544203899 (Fri Dec 07 2018 09:31:39 GMT-0800 (PST))
GETH NODE: INFO [12-07|09:31:52.558] Imported new block headers               count=0    elapsed=252.781µs number=6843869 hash=7fe7b3…c3f54b ignored=4

GETH NODE: INFO [12-07|09:31:52.733] Imported new block headers               count=0    elapsed=189.441µs number=6843868 hash=4fdc4e…f226d7 ignored=3

GETH NODE: INFO [12-07|09:32:02.926] Imported new block headers               count=1    elapsed=5.056ms   number=6843870 hash=5df67b…a3cee4

GETH NODE: INFO [12-07|09:32:02.941] Imported new block headers               count=0    elapsed=63.307µs  number=6843870 hash=5df67b…a3cee4 ignored=1

GETH NODE: INFO [12-07|09:32:06.276] Imported new block headers               count=1    elapsed=5.342ms   number=6843871 hash=d380d6…12e35a

{ Error: no suitable peers available
    at parseEthereumResponse (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)
    at responseHandler (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:46:7)
    at errorHandler (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:36:16)
    at /Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:55:7
    at store.dispatch (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/reset-state.js:45:9)
    at WsTransport.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/transport/ws-transport.js:57:5)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -32000 }
{ Error: no suitable peers available
    at parseEthereumResponse (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)
    at responseHandler (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:46:7)
    at errorHandler (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:36:16)
    at /Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:55:7
    at store.dispatch (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/reset-state.js:45:9)
    at WsTransport.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/transport/ws-transport.js:57:5)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -32000 }
augur-node start: Controller Match Lookup Error. Check if universe "0xe991247b78f937d7b69cfc00f1a487a293557677" exists. no suitable peers available
[09:32:22.947] [info] Restarting Server
Shutdown Augur Node Server
[09:32:22.947] [info] Calling Augur Node Controller Shutdown
[09:32:22.948] [info] Stopping Augur Node Server
[09:32:24.951] [info] Starting Server
1000 3
connecting to augur-node: undefined
connecting to ethereum-node: {"http":"http://127.0.0.1:8545","ws":"ws://127.0.0.1:8546"}
websocket ws://127.0.0.1:8546 opened
could not connect to ethereum-node at {"http":"http://127.0.0.1:8545","ws":"ws://127.0.0.1:8546"} { Error: no suitable peers available
    at parseEthereumResponse (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)
    at responseHandler (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:46:7)
    at errorHandler (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:36:16)
    at /Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:55:7
    at store.dispatch (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/reset-state.js:45:9)
    at WsTransport.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/transport/ws-transport.js:57:5)
    at W3CWebSocket._dispatchEvent [as dispatchEvent] (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/yaeti/lib/EventTarget.js:107:17)
    at W3CWebSocket.onMessage (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/W3CWebSocket.js:234:14)
    at WebSocketConnection.<anonymous> (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/W3CWebSocket.js:205:19)
    at emitOne (events.js:116:13)
    at WebSocketConnection.emit (events.js:211:7)
    at WebSocketConnection.processFrame (/Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /Applications/Augur.app/Contents/Resources/app.asar/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9) code: -32000 }
augur-node start: Could not connect via augur.connect Error: Connection failed
```

**Comment by adrake33** [comment]
Talked to @epheph about this. There isn't really anything we can do to fix this, but we can improve the error message to be clearer.  I saw the following error when trying to reproduce this:

![Screen Shot 2018-12-08 at 9.16.36 AM.png](https://images.zenhubusercontent.com/5bff29dc5cb43a45a18add9f/4f490e5a-ef1a-47ff-a58f-cafe15e283f4)

Scott is going to update the error to be more helpful.

**Comment by adrake33** [comment]
Alex said this is probably resolved and can be closed.
