### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by tinybike** [AugurProject/augur#720]
augur tests are failing for me with this error:
```
  1) augur-ui-react-components market state orderBook should receive an orderBook and be an object:
     AssertionError: market.orderBook isn't defined: expected undefined to not equal undefined
      at Function.r.isDefined (node_modules/augur-ui-react-components/build/components.jsx:2:8150)
      at Context.<anonymous> (node_modules/augur-ui-react-components/build/components.jsx:20:18388)

  2) augur-ui-react-components market state orderBook should be an object:
     AssertionError: market.orderBook isn't an object: expected undefined to be an object
      at Function.r.isObject (node_modules/augur-ui-react-components/build/components.jsx:2:8332)
      at Context.<anonymous> (node_modules/augur-ui-react-components/build/components.jsx:20:18491)
```
The tests are failing on [travis](https://travis-ci.org/AugurProject/augur/builds/147339127) as well.  Am not sure how this commit was pushed since the tests don't pass, but I'm currently unable to push to the augur repo b/c pre-push hooks include npm test.

**Comment by priecint** [comment]
Fixed by https://github.com/AugurProject/augur/commit/043003cccea71b6a346fffd62cde19f2a89beb24
