### ISSUE TITLE
Liquidity check is broken (Dexie error related to MarketDB)

### ISSUE THREAD

**Issue by robert-e-davidson3** [AugurProject/augur#7906]
I'm seeing this error repeated on v2.augur.net, though only the first instance is this detailed:
```
Uncaught (in promise) DexieError {_e: Error
    at getErrorWithStack (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:18826…, name: "DataError", message: "Failed to execute 'cmp' on 'IDBFactory': The param…n 'IDBFactory': The parameter is not a valid key.", inner: DOMException: Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key.
    at htt…}inner: DOMException: Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key.
    at https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:237155
    at https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:221592
    at IDBRequest.guardedCallback (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:253677)message: "Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key.↵ DataError: Failed to execute 'cmp' on 'IDBFactory': The parameter is not a valid key."name: "DataError"_e: Error
    at getErrorWithStack (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:188260)
    at new DexieError (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:190473)
    at DexiePromise.rejectionMapper (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:290045)
    at handleRejection (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:197041)
    at IDBRequest.guardedCallback (https://v2.augur.net/augur~47dad47d.574ee895e0235eccf72e.js:2:253706)stack: (...)get stack: ƒ ()arguments: (...)caller: (...)length: 0name: "get"prototype: {constructor: ƒ}__proto__: ƒ ()[[FunctionLocation]]: augur~47dad47d.574ee895e0235eccf72e.js:2[[Scopes]]: Scopes[2]__proto__: DexieError
(anonymous) @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
async function (async)
(anonymous) @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
setInterval (async)
MarketDB @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
initializeDB @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
async function (async)
initializeDB @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
createAndInitializeDB @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
createServer @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
exports.startServerFromClient @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
connect @ augur~64216fa6.aaf3fe52babedd6794e2.js:2
connect @ augur~5a11b65b.4a2813fc78deed155f91.js:1
(anonymous) @ augur~5a11b65b.4a2813fc78deed155f91.js:1
setTimeout (async)
(anonymous) @ inpage.js:1
write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
_write @ inpage.js:1
b @ inpage.js:1
(anonymous) @ inpage.js:1
v.write @ inpage.js:1
y @ inpage.js:1
h @ inpage.js:1
s.emit @ inpage.js:1
_ @ inpage.js:1
w @ inpage.js:1
b.push @ inpage.js:1
o._onMessage @ inpage.js:1
postMessage (async)
o._write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
_write @ contentscript.js:1
b @ contentscript.js:1
(anonymous) @ contentscript.js:1
v.write @ contentscript.js:1
y @ contentscript.js:1
h @ contentscript.js:1
s.emit @ contentscript.js:1
_ @ contentscript.js:1
w @ contentscript.js:1
b.push @ contentscript.js:1
o._onMessage @ contentscript.js:1
```

Following the error to the (transpiled) source, it's coming from here:
```
                    !liquidityCheckInterval) {
                        liquidityCheckInterval = setInterval(async()=>{
                            if (liquidityDirty.size > 0) {
                                const marketIdsToCheck = Array.from(liquidityDirty);
                                await this.syncOrderBooks(marketIdsToCheck),
                                liquidityDirty.clear()
                            }
                        }
                        , 6e4)
```

Which is in `packages/augur-sdk/src/state/db/MarketDB.ts:77` as:
```
// Don't call this interval during tests
    if (process.env.NODE_ENV !== 'test') {
      if (!liquidityCheckInterval) {
        // call recalc liquidity every min.
        const ONE_MIN_IN_MS = 60000;
        liquidityCheckInterval = setInterval(async () => {
          if (liquidityDirty.size > 0) {
            const marketIdsToCheck = Array.from(liquidityDirty) as string[];
            await this.syncOrderBooks(marketIdsToCheck);
            liquidityDirty.clear();
          }
        },ONE_MIN_IN_MS);
      }
    }
```

**Comment by pgebheim** [comment]
@nuevoalex -- Any idea....

**Comment by pgebheim** [comment]
Alex did a PR for the locking late last week
