### ISSUE TITLE
[BUG] Error: eth_call returned no data (0x)

### ISSUE THREAD

**Issue by petong** [AugurProject/augur#898]
### Summary
We had this error show up in augur-node against Alchemy's rinkeby endpoint, and this morning I had the error with augur-app against our rinkeby endpoint, causing the app to crash and quit.

```
[08:55:31.601] [info] new block: 3753756, 1548435298 (Fri Jan 25 2019 08:54:58 GMT-0800 (PST))
[08:55:31.613] [info] Processing 8 logs
[08:55:41.817] [info] AugurNodeServer requestLatestSyncedBlock
[08:55:44.340] [error] Fatal Error, shutting down servers Error: eth_call returned no data (0x)
    at parseEthereumResponse (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/decode-response/parse-ethereum-response.js:8:47)
    at responseHandler (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:46:7)
    at errorHandler (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:36:16)
    at /Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/rpc/blockchain-message-handler.js:55:7
    at store.dispatch (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/redux-thunk-subscribe/src/index.js:10:18)
    at Object.<anonymous> (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/reset-state.js:45:9)
    at HttpTransport.<anonymous> (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/ethrpc/src/transport/http-transport.js:80:21)
    at Request.self.callback (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/request/request.js:186:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/request/request.js:1163:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Volumes/Augur 1.10.0/Augur.app/Contents/Resources/app.asar/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1090:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

[08:55:44.377] [info] augur-node start: eth_call returned no data (0x)
[08:55:44.659] [info] mainWindow on closed
[08:55:44.660] [info] Shutdown Augur Node Server
[08:55:44.660] [info] Calling Augur Node Controller Shutdown
[08:55:44.661] [info] Stopping Augur Node Server
[08:55:44.661] [info] Stopping Augur UI Server
[08:55:44.661] [info] Stopping geth process
```

**Comment by petong** [comment]
not sure if this helps, but I just got the error testing out docker image builds and the error popped up deploying to a local image:

https://gist.github.com/petong/da66ee83657a02eb3ff0bf80629add89

**Comment by ryanberckmans** [comment]
@petong do you have the specific ethrpc endpoint that generated that error in docker image?

**Comment by ryanberckmans** [comment]
Unactionable right now.

Latest status

* ethrpc library needs architectural rework for better error handling, but this is less of an urgent need because:
* Alchemy returns "no data(0x)" very infrequently, to the point where we have trouble verifying instances of this error
